---
version: '2'

services:
  mail:
    # Dummy email client for development, see ./README.md.
    image: mailhog/mailhog
    ports:
      - "8025"

  node:
    build:
      context: .
      dockerfile: Dockerfile-dev
